spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    password: 'basec '
    url: jdbc:postgresql://localhost/base_c
    username: basec
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: 'basec'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

